pool:
  vmImage: 'windows-2019'

variables:
  - group: 'Secure Variable Group'

steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: production-keys.csv
      
  - powershell: ./build.ps1
    displayName: 'Build'
    env:
      API_KEY: $(API_KEY)

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Agent.TempDirectory)' 
